### PR TITLE
akleventis prod bugs

### PR DESCRIPTION
**Pull request by akleventis**
I noticed some bugs on production. 
- color missing due to css issues
- missing icon in extension overview page

Screen Shot 2022-06-05 at 13 04 29

- null error which was only reproducible if no tabs have ever been set (kind of weird)
- added zoom functionality. Talked to some co-workers about it and they agreed having two zoom options would be handy since the smaller was preferred amongst them.

### CODE REVIEW

**Comment by akleventis** [comment]
Before
---
https://user-images.githubusercontent.com/64287087/172061536-e72fc347-ddb6-48b4-9563-4c0f976e6f9d.mov

**Comment by akleventis** [comment]
After
---

https://user-images.githubusercontent.com/64287087/172061555-45a07ac0-7f6d-4eac-ab99-19a4f171fe55.mov

**Comment by akleventis** [comment]
Before
---

**Comment by akleventis** [comment]
After
---

**Review by furofo — APPROVED** [review]
I noticed that bug as well, nice find and I like the zoom functionality as well. I think it may be good idea to save the zoom preferences to the google profile as well, so it loads the first time to what the user has set. I may work on that and put it on chrome store  as another update.

**Comment by akleventis** [comment]
@furofo sounds good to me. There's just some bugs still that prevent auto grouping. Been working on it for a bit but haven't made much progress. I'll keep on trucking 👍🏻

**Comment by akleventis** [comment]
@furofo fixed the errors, the ungrouping logic was just a bit off. It's all working now. Do you think it'd be a good idea to push these changes to the chrome store so the extension is in a working state? then continue on with storing zoom preferences in a later release?

**Comment by akleventis** [comment]
Also here is a link I made that could replace the long URL (see picture)

https://bit.ly/auto-tab-groups

Screen Shot 2022-06-08 at 00 24 33

**Comment by furofo** [comment]
Yeah man I will submit the changes, and work on adding the saving to profile this week. On a side note how do you feel about it ungrouping on its own when a tab reloads and there is no match, I am thinking I may take that functionality out.

**Comment by akleventis** [comment]
> Yeah man I will submit the changes, and work on adding the saving to profile this week. On a side note how do you feel about it ungrouping on its own when a tab reloads and there is no match, I am thinking I may take that functionality out.

@furofo I personally think the tab *should* ungroup if there is no match. But I do see the other use case where you wouldn't want it to ungroup. What if we made a new branch introducing a settings page? Where the user can choose their zoom preference, ungroup preferences, and provide the youtube tutorial link

settings
---
- `ungroup on new url: on/off`
- `zoom preference: reg/lg`
- `youtube how to link`

**Comment by furofo** [comment]
Yeah I was thinking something similar. We could also make a landing page on
install as well

**Comment by akleventis** [comment]
that'd be great as well. What do you think about creating a new feature
branch to introduce these changes, could help with collaboration?

**Comment by furofo** [comment]
Yeah sounds good

**Comment by furofo** [comment]
I will create the branch tonight and work on the splash and settings
screens then over these next couple of weeks

**Comment by akleventis** [comment]
sounds good!

**Pull request merged**
